In [2]:
import pandas as pd
import numpy as np
import plotly
import matplotlib.pyplot as plt

In [3]:
import plotly.graph_objects as go

In [5]:
df_agg = pd.read_csv('all_aggregated.csv')

In [10]:
df_agg.describe()

,Unnamed: 0,user,duration,totalDistancekM,L_total,R_total,drive_night,jrny,average_duration,average_distance,...,secondary,secondary_link,primary_link,tertiary_link,construction,living_street,pedestrian,road,footway,track
count,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,...,34.000000,34.000000,34.000000,34.000000,34.0,34.0,34.0,34.0,34.0,34.0
mean,16.500000,2.911765,47869.676471,433.352321,688.264706,636.352941,4.411765,64.647059,861.485042,9.509306,...,47.173758,0.034618,0.099500,0.184882,0.0,0.0,0.0,0.0,0.0,0.0
std,9.958246,1.356637,30441.177016,304.139942,638.991313,610.287954,4.684712,40.985498,515.122364,11.038185,...,45.721326,0.039962,0.144726,0.259165,0.0,0.0,0.0,0.0,0.0,0.0
min,0.000000,1.000000,7245.000000,46.024304,61.000000,64.000000,0.000000,9.000000,437.295652,2.301215,...,1.226319,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,8.250000,2.000000,25212.000000,213.114004,221.500000,214.250000,1.000000,25.000000,579.889474,4.826502,...,21.860920,0.002292,0.026788,0.003576,0.0,0.0,0.0,0.0,0.0,0.0
50%,16.500000,3.000000,45653.500000,401.311464,546.500000,452.000000,2.000000,62.000000,680.616835,5.769401,...,35.114375,0.014340,0.066389,0.065347,0.0,0.0,0.0,0.0,0.0,0.0
75%,24.750000,4.000000,60701.000000,534.626082,838.750000,712.000000,7.000000,96.500000,846.943304,7.509567,...,56.437292,0.062483,0.112500,0.222517,0.0,0.0,0.0,0.0,0.0,0.0
max,33.000000,5.000000,131766.000000,1577.300184,2651.000000,2516.000000,19.000000,152.000000,2608.933333,52.576673,...,199.127847,0.133056,0.793750,1.109861,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_agg['Hard_Acc'] = df_agg['Overall_Total_Acc']/df_agg['Overall_Hard_Acc']
df_agg['Hard_Ret'] = df_agg['Overall_Total_Ret']/df_agg['Overall_Hard_Ret']

In [ ]:
display = ['average_duration', 'average_distance', 'L_total', 'R_total', 'drive_night', 'jrny', '']

In [ ]:
fig = go.Figure()

for column in df_stocks.columns.to_list():
    fig.add_trace(
        go.Scatter(
            x = df_stocks.index,
            y = df_stocks[column],
            name = column
        )
    )
    
fig.update_layout(
    updatemenus=[go.layout.Updatemenu(
        active=0,
        buttons=list(
            [dict(label = 'All',
                  method = 'update',
                  args = [{'visible': [True, True, True, True]},
                          {'title': 'All',
                           'showlegend':True}]),
             dict(label = 'MSFT',
                  method = 'update',
                  args = [{'visible': [True, False, False, False]}, # the index of True aligns with the indices of plot traces
                          {'title': 'MSFT',
                           'showlegend':True}]),
             dict(label = 'AAPL',
                  method = 'update',
                  args = [{'visible': [False, True, False, False]},
                          {'title': 'AAPL',
                           'showlegend':True}]),
             dict(label = 'AMZN',
                  method = 'update',
                  args = [{'visible': [False, False, True, False]},
                          {'title': 'AMZN',
                           'showlegend':True}]),
             dict(label = 'GOOGL',
                  method = 'update',
                  args = [{'visible': [False, False, False, True]},
                          {'title': 'GOOGL',
                           'showlegend':True}]),
            ])
        )
    ])

fig.show()